### ISSUE TITLE
içeriklerin görüntülenmesi daha kullanışlı olabilir

### ISSUE THREAD

**Issue by icyertugay** [muaz742/cok-guzel-bir-orman#5]
https://github.com/muaz742/cok-guzel-bir-orman/blob/master/docs/iceriklik.md

ekran içeriklerinin olduğu tablo mobil cihazlardan girildiğinde pek kullanışlı değil. daha kullanışlı hale getirilebilir.

**Comment by muaz742** [comment]
katılıyorum. düzenlemeyi ve odaklanmayı kolaylaştırmak için daha verimli bir görünüm uygulanabilir.

**Comment by icyertugay** [comment]
Sayfanın amacı seçim ve sonuç bazında sonuçları geliştirmekse; görünümü seçim ve sonuç ilişkisiyle sınırlamak işe yarayabilir.

**Comment by muaz742** [comment]
2 tip görüntüleme tavsiye edeceğim.

maddeli görüntüleme örneği;

- ekran numarası: 12
- başlık: hangi hayvan?
- yazı: hayvan seç
- seçim numarası: 6
- seçim: hipopotam
- temsil değeri: karakter yapısı
- duru tanım: bu senin hipopotam olduğunu gösterir
- tugaydan gelen: sen muhteşem bir hipopotamsın

tablolu görüntüleme örneği;

|ekran|12|
|---|---|
|başlık|hangi hayvan?|
|yazı|hayvan seç|
|seçim numarası|6|
|seçim|hipopotam|
|temsil değeri|karakter yapısı|
|duru tanım|bu senin hipopotam olduğunu gösterir|
|tugaydan gelen|sen muhteşem bir hipopotamsın|

**Comment by icyertugay** [comment]
Tablolu görüntülemenin görünümü bile maddeli görüntülemeden iyi.

**Comment by muaz742** [comment]
|ekran:seçim|12:6|
|---|---|
|başlık|hangi hayvan?|
|yazı|hayvan seç|
|seçenekler|aslan, tavşan,.., hipopotam|
|seçim|hipopotam|
|temsil değeri|karakter yapısı|
|duru tanım|bu senin hipopotam olduğunu gösterir|
|tugaydan gelen|sen muhteşem bir hipopotamsın|

bu şekilde seçim ile ekran bilgisini bir araya toparladım. ayrıca soruya ait seçenekleri de ekledim. böylelikle soruyu hatırlamayı kolaylaştırıcı bir unsur oluş düşüncesindeyim.

**Comment by icyertugay** [comment]
Ayrımı netleştirmek için "seçim" yerine "ilgili seçim" yazılabilir. Ve biraz da stil düzenlemesi de fena olmaz gibi.

**Comment by muaz742** [comment]
|ekran : seçim|12:6|
|---|---|
|**başlık**|hangi hayvan?|
|**yazı**|hayvan seç|
|**seçenekler**|*aslan, tavşan,.., hipopotam*|
|**seçim**|hipopotam|
|**temsil değeri**|karakter yapısı|
|**duru tanım**|bu senin hipopotam olduğunu gösterir|
|**tugaydan gelen**|sen muhteşem bir hipopotamsın|
|**öneri**|*önerilen geliştirmeyi buraya yazabilirsin*|

bu görünüme ne dersin?

**Comment by icyertugay** [comment]
Beğendim. Bence tamamdır.

**Comment by muaz742** [comment]
uyguluyorum 👌

**Comment by muaz742** [comment]
https://github.com/muaz742/cok-guzel-bir-orman/commit/deb0c67fcafd92b5472df5df6db3b052e2c61be5

görünüm tanımlandı
