### ISSUE TITLE
Soru Sayısı

### ISSUE THREAD

**Issue by cmlcrn17** [muaz742/cok-guzel-bir-orman#6]
Merhaba

Toplam soru sayısının görüntülemesi gerektiğini düşünüyorum.
Kullanıcı soruları cevaplarken bu yürüyüşün ne kadar zaman alacağına dair bir fikri olmazsa yarım bırakıp çıkabilir.

**Comment by muaz742** [comment]
Merhaba.

Öncelikle kullanım deneyimini paylaştığın için teşekkür ederim.
Okuduğum gibi aynı kaygıyı hissettim. 
Aynı zamanda ekranda soru sayısını görüntülemek ile tasarımın sadeliğini kalabalıklaştırmaktan da kaygılandım.
Kullanıcının ilerlemesini görüntülemesi için https://github.com/muaz742/cok-guzel-bir-orman/commit/54ecb79b9bb530e2943217fbe5e92784f3e80f3e şeklinde bir çözüm geliştirdim.

**Comment by cmlcrn17** [comment]
Elinize sağlık.
